FROM node:20-alpine


WORKDIR /app


COPY package.json package-lock.json ./


RUN npm install

RUN npm install -g nodemon

COPY . .


# RUN npm run build


EXPOSE 3000


# CMD ["npm", "run", "start"]

CMD ["npx", "next", "dev"]